<?php

namespace Altaway\OfferBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Altaway\OfferBundle\Entity\Offer;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository
{

    public function getLastOffers($locale){

        $qb = $this->createQueryBuilder('o');

        $qb->where("o.isEnable = 1")
            ->andwhere("o.language = :locale")
            ->orderBy('o.publishAt', 'DESC')
            ->setParameter("locale", $locale);
        return $qb->getQuery()->setMaxResults(9)->getResult();

    }
}
