# app/config/routing.yml

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

app_Altaway_pages:
    resource: '@AltawayPageBundle/Resources/config/routing.yml'

app_altaway_offers:
    resource: '@AltawayOfferBundle/Resources/config/routing.yml'

fos_user:
   resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sizannia_editor:
    resource: "@SizanniaEditorBundle/Resources/config/routing.xml"