# Altaway/UserBundle/Resources/config/services.yml
imports:
    - { resource: admin.yml }

services:
#    altaway_user.example:
#        class: Altaway\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    fos_user.registration.form.type:
        class: Altaway\UserBundle\Form\Type\RegistrationFormType
        tags:
             - { name: 'form.type', alias: 'fos_user_registration' }
        arguments:
             - %fos_user.model.user.class%

    fos_user.profile.form.type:
            class: Altaway\UserBundle\Form\Type\ProfileFormType
            tags:
                 - { name: 'form.type', alias: 'fos_user_profile' }
            arguments:
                 - %fos_user.model.user.class%
